
services:
  db:
    image: postgres:15
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
     - "5432:5432"


  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file: .env


volumes:
   pg_data:
